<?php

namespace AppBundle\Repository;

/**
 * ComteSocialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComteSocialRepository extends \Doctrine\ORM\EntityRepository
{
}
